This fixed the resizing issue on mobile for the calendar
untrobotics/website pull request #90
Opened 2021-09-03 00:38 UTC by henlegay

2021-09-03 23:15 UTC, sebastian-king commented
This does indeed work! Nice job deploying it to dev. I think there are some things we want to discuss about this task in general, such as if we want to stick with the Google calendar classic view or move to something more modern (I think we previously talked about finding a better calendar library?). We can talk about these and review this PR together in our regularly scheduled meetings that @Peyton232 needs to schedule!

2021-09-03 23:50 UTC, ntindle commented
Let’s merge this since it works now and talk about upgrading the calendar later?

2021-09-03 23:53 UTC, sebastian-king commented
Good point! Once the .idea files have been removed I’m happy to approve the PR

2021-09-05 22:44 UTC, ntindle commented
You've done it!

2021-09-05 22:44 UTC, ntindle approved these changes

2021-09-05 22:44 UTC, ntindle commented on events.php
> +    <style>
@sebastian-king are we putting stuff in global CSS?

2021-09-05 22:45 UTC, Peyton232 commented
looks good

2021-09-05 22:45 UTC, sebastian-king requested changes
Can we re-add *.log to the .gitignore file?

2021-09-05 22:51 UTC, ntindle submitted a review, later dismissed

2021-09-05 22:51 UTC, ntindle commented
LGTM (looks good to me)

2021-09-05 22:55 UTC, Peyton232 commented
Shouldn't we make it *.idea

2021-09-05 23:05 UTC, ntindle commented
.idea removes the folder 

*.idea removes anything with that extension

2021-09-05 23:06 UTC, ntindle commented
.idea/
And 

*.idea could be prudent

2021-09-05 23:07 UTC, ntindle commented
Just copy and paste this to the end of the file and let's call it a day

https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

2021-09-05 23:26 UTC, sebastian-king submitted a review, later dismissed

2021-09-06 18:59 UTC, ntindle approved these changes
LGTM for real this time

2021-09-06 18:59 UTC, merged

2021-09-06 19:19 UTC, sebastian-king commented
Now that the PR is merged can you update the Jira ticket status to Ready for Production?